Fix/challenge issues parallel
0chain/blobber pull request #1007
Opened 2023-03-22 15:57 UTC by lpoli

### Changes

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-03-27 18:35 UTC, dabasov requested changes

2023-03-27 18:35 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +		// offset += len(challengeResponse.Challenges)
this query won't work without offset, every time you request you will get the same challenge, so you will duplicate the work

2023-03-27 18:35 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +		d := time.Since(challengeRespTime)
handle context to break the loop

2023-03-27 18:35 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +			defer func() {
don't use several defer blocks

2023-03-27 18:35 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/protocol.go
> +			for {
this will cause spin wait, avoid it by all means

2023-03-27 18:35 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/protocol.go
> +func ProcessChallengeTransactions(ctx context.Context) {
this func should be rewritten

2023-04-11 02:36 UTC, lpoli commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +		// offset += len(challengeResponse.Challenges)
Wouldn't `from` param exactly filter it? Otherwise what use is of `from` param?
If we use both `from` and `offset` then it seems problem to me.

2023-04-11 02:40 UTC, lpoli commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +			defer func() {
Why so?
There are only two defer blocks.

2023-04-11 02:41 UTC, lpoli commented on code/go/0chain.net/blobbercore/challenge/protocol.go
> +			for {
No it won't. The loop is protected by lock

2023-05-01 20:54 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/protocol.go
> +			for {
how it can help? you will enter the loop go to default and enter it again. we should never use spin waits

2023-05-15 03:49 UTC, closed without merging