[WIP] Fix - challenge ordering issue
0chain/blobber pull request #1030
Opened 2023-04-12 10:55 UTC by din-mukhammed

### Changes

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-04-15 18:31 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | reward_test_timeout  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/challenge-issues-parallel-din  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-05-10 18:57 UTC, dabasov requested changes

2023-05-10 18:57 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +// be descending order.
why descending, I believe we want to process challenges starting from the earliest up to latest

2023-05-10 18:57 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +				updateChallengeStatus(chalEntity, Cancelled, "Completed but cancelled due to error: "+err.Error())
will we write twice in chalEntity.StatusCh?

2023-05-10 20:16 UTC, dabasov requested changes

2023-05-10 20:16 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +	unProcessedChallengeCh = make(chan *ChallengeEntity, 1)
is it enough to have buffer so small?

2023-05-10 20:16 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +			err = <-chalEntity.ErrCh
what if no error is written, will it hang forever?

2023-05-10 20:16 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/challenge.go
> +			chalEntity.Status = Committed
why is it committed?

2023-05-10 20:16 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/protocol.go
> +	stopToProcessCh := make(chan *ChallengeResponse, 1)
why do we need buffered channels here?

2023-05-16 08:00 UTC, closed without merging