add geolocation fields to the config
0chain/blobber pull request #104
Opened 2021-05-02 21:57 UTC by andrenerd

@Sriep 
Need you input. Thanks.

- how about to move the GeolocationConfig struct to 0chain main app, specifically here (and import from there to specific services, such as blobber):
https://github.com/0chain/0chain/blob/master/code/go/0chain.net/chaincore/config/config.go

- it was also mentioned to add geolocation props to storagsc and minersc smart contracts too. does it mean, the props should be added to these structs specifically (currently they have near to zero fields)?
https://github.com/0chain/0chain/blob/ee5704d2617f42dcf857270cf73be44a9e5c523b/code/go/0chain.net/smartcontract/storagesc/sc.go#L24
https://github.com/0chain/0chain/blob/ee5704d2617f42dcf857270cf73be44a9e5c523b/code/go/0chain.net/smartcontract/minersc/sc.go#L51

2021-05-07 17:52 UTC, Sriep commented
Needs to add geo-location to blobber.yaml, and pass the geo-location information to 0cahin when registering blobber.

Part of https://github.com/0chain/0chain/issues/238. There is no urgency to merge this Pr until the `0cahin` and `zboxcli` parts of issue 238 are ready.

2021-06-06 09:00 UTC, Sriep commented
I think we should [validate longitude and latitude values.](https://stackoverflow.com/questions/15965166/what-are-the-lengths-of-location-coordinates-latitude-and-longitude). Confirm:
* Latitude : max/min 90.0000000 to -90.0000000
* Longitude : max/min 180.0000000 to -180.0000000
Should be good enough.

2021-06-07 04:04 UTC, andrenerd commented
@Sriep thanks. added. please, recheck.
ps. not found better place to put the validation, any suggestion are welcome.

2021-06-08 16:02 UTC, Sriep requested changes

2021-06-08 18:14 UTC, Sriep commented
Merge in the latest master changes, as I think that might fix the failing unit test check.

2021-06-08 22:44 UTC, andrenerd commented on code/go/0chain.net/blobbercore/config/config.go
> +			g.Latitude = float64(0.00)
Ok. If there should be error, let it be panic error.
As passing regular error and forcing higher level components to deal with it makes no sense.

2021-06-08 22:50 UTC, andrenerd commented on code/go/0chain.net/core/transaction/entity.go
> +	// reserved / Accuracy float64 `mapstructure:"accuracy"`
Everything except this point will be update. I prefer to keep this, as a clue for potential upgrades.

2021-06-09 06:53 UTC, Sriep commented
Please merge in the latest master changes. You need the fix to the unit test checks.

2021-06-09 08:22 UTC, Sriep requested changes

2021-06-09 08:22 UTC, Sriep commented on code/go/0chain.net/blobbercore/config/config.go
> +	// reserved / Accuracy float64 `mapstructure:"accuracy"`
Please remove. It just confuses people and uses up space.

2021-06-09 08:22 UTC, Sriep commented on code/go/0chain.net/blobbercore/readmarker/entity.go
>  	var (
If there are no meaningful changes to entity.go, revert changes and remove from PR.

2021-06-09 08:22 UTC, Sriep commented on code/go/0chain.net/core/transaction/entity.go
> +	// reserved / Accuracy float64 `mapstructure:"accuracy"`
Remove unnecessary comments.It just confuses people.

2021-06-09 23:48 UTC, merged