Add resp msg in create conneciton obj api
0chain/blobber pull request #1123
Opened 2023-06-10 14:42 UTC by Roshan-Mehta

### Changes

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-06-12 12:11 UTC, dabasov requested changes

2023-06-12 12:11 UTC, dabasov commented on code/go/0chain.net/blobbercore/blobberhttp/response.go
> +	Success        bool   `json:"success"`
looks like we don't use this field, let's remove it

2023-06-12 15:29 UTC, Roshan-Mehta commented on code/go/0chain.net/blobbercore/blobberhttp/response.go
> +	Success        bool   `json:"success"`
Which one?

2023-06-12 15:35 UTC, Roshan-Mehta commented on code/go/0chain.net/blobbercore/blobberhttp/response.go
> +	Success        bool   `json:"success"`
Done

2023-06-12 15:56 UTC, dabasov approved these changes
lgtm

2023-06-13 14:06 UTC, service-0chain commented
Manual system tests [cancelled] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/send-resp-create_connection  |
| authorizer  | staging  |
| 0box  | staging  |
| 0dns  | staging  |

2023-06-13 14:39 UTC, merged