[WIP] fix(upload):added ChunkWriter feature on upload. #111
0chain/blobber pull request #115
Opened 2021-05-08 07:50 UTC by cnlangzi

- Added `ChunkWriter` feature on `UploadHanlder.`  It is automate detection, and backwards compatible with old gosdk

2021-05-10 22:00 UTC, andrenerd approved these changes
Cool, but can some extra formatting be done? Please, check comments. Thanks.

2021-05-10 22:00 UTC, andrenerd commented on code/go/0chain.net/blobbercore/filestore/fs_store.go
> +
some blank lines looks pretty sporadic. is based on the logic?

2021-05-11 11:15 UTC, Sriep requested changes
This pr should be linked with the corresponding gosdk PR https://github.com/0chain/gosdk/pull/33

2021-05-11 11:15 UTC, Sriep commented on code/go/0chain.net/blobbercore/filestore/chunk_writer_test.go
> +		assert.Fail(t, "failed to create ChunkWriter", err)
Use require rather than assert, as we want the test to fail on an error.  Same below.

2021-05-12 22:43 UTC, cnlangzi commented
@Sriep  please help to review them again. thanks.

2021-05-12 23:12 UTC, andrenerd approved these changes

2021-05-13 03:25 UTC, vudn95 reviewed
LGTM. However, It's been some typo that needs to be updated.

2021-05-13 03:25 UTC, vudn95 commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
> +		exisitingFileRefSize := int64(0)
typo, please rollback to `existingFileRefSize`

2021-05-13 03:25 UTC, vudn95 commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
> +		if allocationObj.BlobberSizeUsed+(allocationSize-exisitingFileRefSize) > allocationObj.BlobberSize {
typo, please rollback to `existingFileRefSize`

2021-05-13 03:25 UTC, vudn95 commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
> +		allocationChange.Size = allocationSize - exisitingFileRefSize
typo, please rollback to `existingFileRefSize`

2021-05-14 06:24 UTC, andrenerd approved these changes

2021-05-16 14:19 UTC, Sriep approved these changes

2021-05-17 11:58 UTC, merged