Fix fetch open challenge
0chain/blobber pull request #1162
Opened 2023-07-06 20:10 UTC by Hitenjain14

### Changes

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-07-08 14:50 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zboxcli  | users/sunilmhta/fix/2544/updateblobnvalidator  |
| zwalletcli  | sprint-july-1  |
| 0chain  | users/sunilmhta/fix/2544/0chain/blobber-settings  |
| blobber  | sprint-july-1  |
| authorizer  | sprint-july-1  |
| 0box  | staging  |
| 0dns  | staging  |

2023-07-09 20:52 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  | sprint-july-1  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | sprint-july-1  |
| zwalletcli  | sprint-july-1  |
| 0chain  | sprint-july-1  |
| blobber  | fix/open-challenge  |
| authorizer  |   |
| 0box  | sprint-july-1  |
| 0dns  | staging  |

2023-07-11 12:49 UTC, dabasov requested changes

2023-07-11 12:49 UTC, dabasov commented on code/go/0chain.net/blobbercore/allocation/allocationchange.go
> +	tx := datastore.GetStore().GetDB().Begin()
we better store transaction in context, it will make caching much easier
```go
	tx := datastore.GetStore().GetTransaction(ctx)

```

2023-07-11 12:56 UTC, dabasov approved these changes
lgtm

2023-07-12 14:36 UTC, merged