README.md changes
0chain/blobber pull request #1260
Opened 2023-09-21 22:56 UTC by hm90121

-- add blobber build scripts for apple silicon devices

2023-09-22 08:24 UTC, devyetii requested changes

2023-09-22 08:24 UTC, devyetii commented on README.md
> +
Looks fine but please remove line 104 down starting with "For Mac with Apple M1 ..."

2023-09-22 17:46 UTC, Kishan-Dhakan requested changes

2023-09-22 17:46 UTC, Kishan-Dhakan commented on README.md
> +Sometimes in Apple Silicon devices (m1/m2 macbooks), buildx will not work for build scripts. To force a regular blobber build, run the following instead of the build commands mentioned above:
Please check and remove/clean up other references to M1 or apple devices

2023-09-22 17:55 UTC, Kishan-Dhakan requested changes
Instead of a Note, please add a heading so that the following structure is used:

## Building and Starting the Nodes
### Building on standard hardware
... content
### Building on apple silicon (M1/M2 chips)
... content

2023-09-28 08:09 UTC, Kishan-Dhakan approved these changes

2023-09-28 08:10 UTC, merged

2023-09-28 16:31 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  | staging  |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |