Cleanup worker for challenge tables
0chain/blobber pull request #1278
Opened 2023-10-04 14:42 UTC by Hitenjain14

### Changes

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2023-10-04 17:12 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  | feat/challenge-cleanup  |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-10-05 20:34 UTC, dabasov approved these changes
lgtm

2023-10-05 20:36 UTC, dabasov requested changes

2023-10-05 20:36 UTC, dabasov commented on code/go/0chain.net/blobbercore/challenge/timing.go
> +		return db.Model(&ChallengeTiming{}).Unscoped().Delete(&ChallengeTiming{}, "created_at_blobber < ?", time.Now().Add(-cleanupGap).Unix()).Error
can we have cleanupGap in configs?

2023-10-06 17:57 UTC, Hitenjain14 commented on code/go/0chain.net/blobbercore/challenge/timing.go
> +		return db.Model(&ChallengeTiming{}).Unscoped().Delete(&ChallengeTiming{}, "created_at_blobber < ?", time.Now().Add(-cleanupGap).Unix()).Error
Move the challenge one to config

2023-10-06 18:51 UTC, dabasov approved these changes
lgtm

2023-10-10 12:23 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | false  |
| system-tests  |   |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  |   |
| zwalletcli  |   |
| 0chain  |   |
| blobber  | sprint-1.11  |
| authorizer  |   |
| 0box  |   |
| 0dns  |   |

2023-10-10 17:24 UTC, dabasov approved these changes
lgtm

2023-10-10 17:24 UTC, merged