153 grpc copy object handler
0chain/blobber pull request #155
Opened 2021-05-26 08:42 UTC by senpathi

relates to #153 

copy object handler migrated to grpc
tests added

2021-05-30 21:35 UTC, shravanshetty1 requested changes

2021-05-30 21:35 UTC, shravanshetty1 commented on code/go/0chain.net/blobbercore/blobbergrpc/proto/blobber.proto
> +      post: "/v1/file/copy/{allocation}"
v2

2021-05-30 21:35 UTC, shravanshetty1 commented on code/go/0chain.net/blobbercore/handler/object_operation_grpc_handler.go
> +		return nil, common.NewError("invalid_operation", "Invalid client")
Will read this file in next review but please make sure that the changes between this and original is minimal, thanks!

2021-05-31 14:47 UTC, senpathi commented on code/go/0chain.net/blobbercore/blobbergrpc/proto/blobber.proto
> +      post: "/v1/file/copy/{allocation}"
This is fixed

2021-06-15 06:11 UTC, merged