feat(upload):refactor code for file upload/update/delete, and add res…
0chain/blobber pull request #166
Opened 2021-05-27 06:55 UTC by cnlangzi

Checklist:
- Refactor StorageHandler.WriteFile with Factory method pattern. Moved code to `InsertFileCommand`, `UpdateFileCommand` and `DeleteFileCommand` for flexible style
- Added `PATCH` handler as ResumeUpload request
- Added ResumeFileCommand  to process ResumeUpload request
- Added ResumeFileChange.go for file transaction
- Added `StreamMerkleHasher` as stateful merkle tree to compute streaming file
- Added `WriteChunk` in `FileFSStore` to flush chunk to temp file.

2021-06-11 13:48 UTC, cnlangzi commented
`./dev.local/cli.sh` is linked to https://github.com/0chain/blobber/issues/145

2021-06-11 15:44 UTC, cnlangzi commented
@Sriep please help me to review PR if you get some time left , thanks.

2021-06-12 10:46 UTC, Sriep requested changes
Newly written functions need unit tests.

2021-06-12 10:46 UTC, Sriep commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
> +	fmt.Println(rootRef.Hash + ":" + strconv.FormatInt(int64(writeMarker.Timestamp), 10))
Why are your using `fmt.Println` rather than a logger? It its just a debug line please remove.

2021-06-14 23:04 UTC, cnlangzi commented
ignore it first. thanks.

2021-06-14 23:04 UTC, closed without merging

2021-09-06 09:07 UTC, cnlangzi commented
see detail on https://github.com/0chain/blobber/wiki/Features-Upload#upload