multiple handler funcs for  upload handler with different http methods
0chain/blobber pull request #326
Opened 2021-08-28 13:37 UTC by senpathi

Multiple method support from grpc-gateway handlers to upload handler

2021-08-29 12:52 UTC, kushthedude requested changes
This piece of code might have been missed from my previous reviews, would you mind adding error checks in all the three places where we have been injecting custom routes?

2021-08-29 12:52 UTC, kushthedude commented on code/go/0chain.net/blobbercore/handler/grpc_helpers.go
> +	_ = grpcGatewayHandler.HandlePath("PUT", "/v1/file/upload/{allocation}",
Why the error is ignored in each place?
```suggestion
	err = grpcGatewayHandler.HandlePath("PUT", "/v1/file/upload/{allocation}",
		if err != nil {
		log.Errorf("failed to add custom route: %v", err)
		panic(err)
	}
```

2021-08-29 16:14 UTC, senpathi commented on code/go/0chain.net/blobbercore/handler/grpc_helpers.go
> +	_ = grpcGatewayHandler.HandlePath("PUT", "/v1/file/upload/{allocation}",
okay sure

2021-08-31 14:11 UTC, kushthedude approved these changes

2021-08-31 14:11 UTC, merged