lint fixes
0chain/blobber pull request #37
Opened 2021-03-25 06:12 UTC by ronaudinho

fixes/defer fixes for all the lints issues:
1. nolint for some unused/deadcode as they may be used somewhere
2. nolint for some parts that require more investigation
3. errcheck: keep current flow, only log error instead of returning it (although for several places, it looks like it makes more sense to return an error instead?)
4. fix other lints issues which look straightforward enough

this PR also serves as preparation for other incoming unit tests PRs, as it would be easier to branch from master with lints fixed.

I'll be commenting some changes for more details.

2021-03-25 06:17 UTC, ronaudinho commented on code/go/0chain.net/blobber/main.go
>  func processMinioConfig(reader io.Reader) error {
there is probably a better way of doing this rather than having to check `scanner.Scan()` after each line?

2021-03-25 06:17 UTC, ronaudinho commented on code/go/0chain.net/blobber/main.go
> +	_ = zcncore.InitZCNSDK(serverChain.BlockWorker, config.Configuration.SignatureScheme)
unchecked and it will fail later on if `InitZCNSDK` throws an error, but perhaps it might be better to fail early?

2021-03-25 06:17 UTC, ronaudinho commented on code/go/0chain.net/blobbercore/allocation/allocationchange.go
> +	"0chain.net/core/logging"
not a fan of [dot](https://github.com/golang/go/wiki/CodeReviewComments#import-dot) [import](https://github.com/golang/go/issues/29326), but most of the codebase uses it, so I can change if necessary.

2021-03-25 06:18 UTC, ronaudinho commented on code/go/0chain.net/blobbercore/allocation/allocationchange.go
> +			logging.Logger.Error("AllocationChangeProcessor_DeleteTempFile", zap.Error(err))
not sure if it makes more sense to break the loop and return an error here, since it will be a departure from the current flow.

2021-03-25 06:22 UTC, ronaudinho commented on code/go/0chain.net/blobbercore/datastore/store.go
> +	return context.WithValue(ctx, CONNECTION_CONTEXT_KEY, db) //nolint:staticcheck // changing type might require further refactor
not sure if it's necessary to create a `type ConnectionContextKey string` for this, but `context.WIthValue` itself warns that key should be of built-in type.

2021-03-25 06:22 UTC, ronaudinho commented on code/go/0chain.net/blobbercore/filestore/fs_store.go
> +	if err := createDirs(rootDir); err != nil {
probably should fail early as well?

2021-03-25 06:24 UTC, ronaudinho commented on code/go/0chain.net/blobbercore/handler/storage_handler.go
> +	statsBytes, _ := json.Marshal(stats)
a simple marshal and unmarshal from struct, probably won't err, but I'm open to suggestion if we should still check for error.

2021-03-25 06:26 UTC, ronaudinho commented
[test passed](https://github.com/ronaudinho/blobber/runs/2190588735?check_suite_focus=true). non-commented changes are most likely of similar types as commented ones.

2021-04-05 17:53 UTC, Sriep requested changes
This PR will unsilence some errors in the project. We want to know about these errors, but need to be prepared. Also I agree this should be moreged before other blobber PRs.

2021-04-05 17:53 UTC, Sriep commented on code/go/0chain.net/core/cache/lru.go
>  	return nil
Return the error. if this breaks something, its something we need to fix.

2021-04-05 17:53 UTC, Sriep commented on code/go/0chain.net/core/common/time.go
I would remove it. Private and looks like an abandoned idea.

2021-04-05 17:53 UTC, Sriep commented on code/go/0chain.net/core/transaction/entity.go
> +	t.zcntxn.SetTransactionHash(t.Hash) //nolint:errcheck // checked in the next step
[This errors](https://github.com/0chain/gosdk/blob/master/zcncore/transaction.go#L400) if the ransaction already exists. Returning this error should fail an attempt to send a transaction that already exists. This seems more useful to the user than a generic "transaction_verify_error" so return it.

2021-04-05 17:53 UTC, Sriep commented on code/go/0chain.net/validator/main.go
> +				txnVerified = true //nolint:ineffassign // probably has something to do with goroutines
This line can saftly be removed as you are just about to return. It has some documentary value, but remove it.

2021-04-05 17:53 UTC, Sriep commented on code/go/0chain.net/validator/main.go
> +	zcncore.InitZCNSDK(serverChain.BlockWorker, config.Configuration.SignatureScheme) //nolint:errcheck // error would be detected later as SDK not initialized
Pass these error up to main and error out from there. The user will likley find this error more useful than any follow up error. Same for wallet infol

2021-04-05 17:53 UTC, Sriep commented on code/go/0chain.net/validatorcore/storage/challenge_handler.go
> +		if err := validationTicket.Sign(); err != nil {
Return this error. Failier to sign looks critical.

2021-04-05 17:53 UTC, Sriep commented on code/go/0chain.net/validatorcore/storage/challenge_handler.go
> +		Logger.Error("ValidationTicket_Sign", zap.String("challenge_id", validationTicket.ChallengeID), zap.Error(err))
Return this error. Failier to sign looks critical.

2021-04-08 20:14 UTC, Sriep approved these changes

2021-04-13 09:00 UTC, merged

2021-04-13 14:34 UTC, shravanshetty1 commented
@ronaudinho lint fixes for `validatorcore/storage` tests are failing test build - kindly fix them

2021-04-26 13:57 UTC, Sriep commented
`validatorcore/storage` test failing.
Lint fix exposed issue fixed in https://github.com/0chain/blobber/pull/80