Expanding unit-tests && fixing issue with renaming dirs
0chain/blobber pull request #386
Opened 2021-10-12 07:19 UTC by moldis

This branch is under WIP yet
Related to https://github.com/0chain/blobber/issues/382

2021-10-22 11:07 UTC, lpoli commented on code/go/0chain.net/blobbercore/reference/ref.go
> +		if cur == "." {
Don't understand what kind of issue it fixes. Can you please show when will `cur == "."` be useful?

Also this function is very inefficient. I know its written by Sarath Ambati.
It should be splitted by `strings` package. `strings.Split(s, "/")`

2021-10-22 11:32 UTC, lpoli commented on code/go/0chain.net/blobbercore/allocation/renamefilechange.go
> +	if len(dirRef.Children) == 0 {
If `dirRef` have no children then I doubt code will reach this line.
It should return error when calling `GetObjectTree` in line 28

Also this function can be highly optimized. 
The `for` loop in line 54 have a single purpose of finding `ref` in rootRef so some other child `refs` can be removed and then calculate Hash of all affected directory `ref`. This `for` loop is very inefficient. We need to refactor it.
Please verify.

2021-10-22 11:36 UTC, lpoli requested changes
One function that needs optimization is `GetReferencePath`. What should be done is, refactor `GetReferencePath` and make respective changes to all the caller.

Anyway `for` loop in line 56 is very inefficient. It should be refactored.

2021-11-16 00:50 UTC, cnlangzi approved these changes

2021-11-16 00:51 UTC, merged