:bug: Reject rename if file already exists
0chain/blobber pull request #390
Opened 2021-10-14 07:22 UTC by moldis

Related to https://github.com/0chain/blobber/issues/389

2021-10-14 08:12 UTC, cnlangzi requested changes

2021-10-14 08:12 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/allocation/renamefilechange.go
> +	_, err = reference.GetObjectTree(ctx, rf.AllocationID, rf.NewName)
It is too heavy to load so many nodes for it?

```
	if path != "/" {
		db = db.Or("path LIKE ? AND allocation_id = ?", (path + "/%"), allocationID)
	} else {
		db = db.Or("path LIKE ? AND allocation_id = ?", (path + "%"), allocationID)
	}
```

do you think it is better to add a simple check function for better sql performance?

2021-10-14 15:23 UTC, moldis commented on code/go/0chain.net/blobbercore/allocation/renamefilechange.go
> +	_, err = reference.GetObjectTree(ctx, rf.AllocationID, rf.NewName)
@cnlangzi Yes, the whole function is very messy and hard to read. I created separate issue to refactor it

2021-11-03 17:47 UTC, kushthedude commented on code/go/0chain.net/blobbercore/allocation/renamefilechange.go
> +	}
```suggestion
	isFilePresent, _ := reference.PathExists(ctx, rf.AllocationID, rf.NewName)
	if isFilePresent {
		return nil, common.NewError("invalid_reference_path", "file already exists")
	}
```

2021-11-03 17:48 UTC, kushthedude approved these changes, later dismissed
Looks good to me @moldis, have made a small grammatical correction. Btw do you mind adding a small unit test to verify this fix?

2021-11-16 00:47 UTC, cnlangzi requested changes

2021-11-16 00:47 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/referencepath.go
> +	db = db.Where(ref).Or("path LIKE ? AND allocation_id = ?", (path + "/%"), allocationID)
do you think `db = db.Where(ref).Or("path = ? AND allocation_id = ?", path , allocationID)` is enough?

2021-11-16 00:47 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/referencepath.go
> +	err := db.Order("level, lookup_hash").Preload(ref.TableName(), func(tx *gorm.DB) *gorm.DB {
`order by` and `preload` should be unnecessary here? please double check it. thanks.

2021-11-17 08:06 UTC, cnlangzi approved these changes

2021-11-17 08:06 UTC, merged