Signature verification in file meta api to ensure authorized access to allocation owner or a registered collaborator
0chain/blobber pull request #394
Opened 2021-10-19 00:27 UTC by iamrz1

2021-10-20 00:29 UTC, cnlangzi requested changes

2021-10-20 00:29 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		return handler(ctx, r)
please save `allocationObj` in context, and in handler , we can get it from context directly. it will save some time to load it again. Because almost handlers will read it again.

2021-10-20 02:16 UTC, iamrz1 commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		return handler(ctx, r)
Yes it will also improve the dry-ness of the code. In that case we'll have to remove all the allocation initialization code from the handlers. That'd be a lot of code rewrites.

2021-10-20 02:19 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		return handler(ctx, r)
@iamrz1  migrate them one by one. It is unnecessary to get it done in one PR if it is too much. But it should be fixed on handlers you are woking on now.

2021-10-26 05:27 UTC, iamrz1 commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		return handler(ctx, r)
I have moved allocation object to context for file-meta/ file-stats handlers. take a look and let me know what you think.

2021-10-26 07:56 UTC, iamrz1 commented on code/go/0chain.net/blobbercore/handler/grpc_handler.go
> +	resp, err := WithReadOnlySignatureVerification(FileMetaHandler)(ctx, r)
@kushthedude what do you think of this approach to address http middlewares in grpc handlers?

2021-10-26 08:13 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/grpc_handler.go
> +	resp, err := WithReadOnlySignatureVerification(FileMetaHandler)(ctx, r)
@kushthedude  do you mean move all middleware to grpc handler instead of http hanlder?

2021-10-26 08:21 UTC, cnlangzi requested changes

2021-10-26 08:21 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		ctx = setupHandlerContext(ctx, r)
you can merge them into one method without another boxing/unboxing from context.

2021-10-26 08:21 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		ctx = setupHandlerContext(ctx, r)
`setupHandlerContext` and `performSignatureVerification`

2021-10-26 08:21 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		ctx = setupHandlerContext(ctx, r)
for example: https://github.com/0chain/blobber/blob/c82cb186436acf6d78bb611d3add8c685978f47d/code/go/0chain.net/blobbercore/handler/handler.go#L76

2021-10-26 08:21 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		ctx = setupHandlerContext(ctx, r)
what difference between `WithReadWriteSignatureVerification` and `WithReadOnlySignatureVerification`?

2021-10-26 08:36 UTC, iamrz1 commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		ctx = setupHandlerContext(ctx, r)
`setupHandlerContext` is being used in other handler functions right now. so it has to stay that way. I can merge `performSignatureVerification` in the parent function, but I kept it that way to keep it available for non-readonly operations using `WithReadWriteSignatureVerification` middleware.

`WithReadOnlySignatureVerification` checks if client has read permission, `WithReadWriteSignatureVerification` checks (according to my interpretation) if client has write permission too. We might use this middleware when we replace existing repetition in handlers with middlewares.

2021-10-26 09:12 UTC, iamrz1 commented on code/go/0chain.net/blobbercore/handler/grpc_handler.go
> +	resp, err := WithReadOnlySignatureVerification(FileMetaHandler)(ctx, r)
No, since I'm doing signature verification from http middlewares, grpc handlers also need to call the http middleware. This is my solution to that problem.

2021-10-26 09:18 UTC, kushthedude commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		if signatureHeader == nil {
Please lets not add additional wrapper over the handlers, gRPC code already takes care of this so lets not make more logical changes here & simply do the signature verification in the handler logic

2021-10-26 09:18 UTC, kushthedude commented on code/go/0chain.net/blobbercore/handler/handler.go
> +			return nil, common.NewErrorf("invalid_allocation", "Missing allocation in context")
This is unrelated to signature verification, either lets do it in other PR or drop it as is as the gRPC takes in allocation & all the other headers into the context & pass through the values using context https://github.com/0chain/blobber/blob/fd2592402e5c95d47f80ea4c3710730d0509c543/code/go/0chain.net/blobbercore/handler/grpc_helpers.go#L32

2021-10-27 06:25 UTC, cnlangzi submitted a review, later dismissed
LGTM. please fix go.mod/go.sum.

2021-10-27 06:27 UTC, kushthedude commented on code/go/0chain.net/blobbercore/handler/grpc_handler.go
> +	resp, err := WithReadOnlySignatureVerification(FileMetaHandler)(ctx, r)
Why would grpc call http?

2021-10-27 08:09 UTC, iamrz1 commented on code/go/0chain.net/blobbercore/handler/grpc_handler.go
> +	resp, err := WithReadOnlySignatureVerification(FileMetaHandler)(ctx, r)
I'm not sure what you mean by this but `resp, err := FileMetaHandler(ctx, r)` is a call to a http handler named `FileMetaHandler`, right? Ergo, my interpretation is that grpc handler is making calls to http habdler.

I just added the same middleware that http handler is using now.

2021-10-27 08:21 UTC, iamrz1 commented on code/go/0chain.net/blobbercore/handler/handler.go
> +			return nil, common.NewErrorf("invalid_allocation", "Missing allocation in context")
`getGRPCMetaDataFromCtx` and the code block in this middleware does not perform the same task, take a look at the codebase, and you'll see.

And codes that are seemingly unrelated to signature verification (getting and setting values in ctx) are part of planned streamlining handler codebase (ie. avoid getting allocation object multiple times or setting values in ctx in different places) as almost all the handlers are performing signature verification anyway.

2021-10-27 08:36 UTC, iamrz1 commented on code/go/0chain.net/blobbercore/handler/handler.go
> +		if signatureHeader == nil {
There's nothing here that repeats codes from gRPC. And there's no logical change, only the verification part is being done before executing the handler.
The reason why the signature verification code is being moved to a middleware is, verification check is a crucial security issue and there has been a separate PR before to address endpoints that were missing it. But the file-stats and file-meta apis still missed verification check because of oversight. Moving verification to a middleware will make it glaringly obvious which endpoints are missing this security check.

2021-11-01 09:45 UTC, kushthedude commented on code/go/0chain.net/blobbercore/handler/handler.go
> +			return nil, common.NewErrorf("invalid_allocation", "Missing allocation in context")
getGRPCMetaDataFromCtx, this takes the value of the allocation from the request, please read the complete code block.

> (ie. avoid getting allocation object multiple times or setting values in ctx in different places) 

The above function does it correctly, anyways go ahead as you like as ultimately grpc is going to replace all this cluttered middlewares

2021-11-01 09:47 UTC, kushthedude submitted a review, later dismissed
Lets merge this as it is a crucial security fix & regarding the discussion on middleware gRPC will have to take rid of them and abstract them into helper utilities. The only reason I was not in favour of middleware because if there was a helper we could have reused it in grpc preprocessing but for middlewares we need to write a custom helper to replace it 😓 


@cnlangzi please do approve and merge

2021-11-09 13:26 UTC, iamrz1 commented
It appears that the issue with go-sdk still has not been resolved. Blobber is still failing tests.

2021-11-09 13:42 UTC, cnlangzi commented
critical security issue, get it merged first.

2021-11-09 13:42 UTC, merged