re-implemented `createdir` and added development toolkits
0chain/blobber pull request #395
Opened 2021-10-19 02:26 UTC by cnlangzi

- Added AutoMigrate feature. see  [detail](https://github.com/0chain/blobber/blob/0aea42103f924138d3cf1896569e6b44e85e8e45/code/go/0chain.net/blobbercore/models)
- Added new blobber hanlder development toolkit for better readable and performance [detail](https://github.com/0chain/blobber/blob/0aea42103f924138d3cf1896569e6b44e85e8e45/code/go/0chain.net/blobbercore/handler/handler.go#L76)
   + Removed transaction from request `WithConnection`.
   + Removed transaction from request `WithReadonlyConnection` 
   + Added [DryRun](https://github.com/0chain/blobber/blob/0aea42103f924138d3cf1896569e6b44e85e8e45/code/go/0chain.net/blobbercore/allocation/dao.go#L42) to prepare statement for speed up sql call
   + Added new [DAO](https://github.com/0chain/blobber/blob/0aea42103f924138d3cf1896569e6b44e85e8e45/code/go/0chain.net/blobbercore/allocation/dao.go#L14) to disable ORM feature.  
   + Add `WithAuth` to verify allocation and signature , and pass it directly without boxing/unboxing from context.Context
- Reimplemented `CreateDir`, and get `zbox list` worked with it.

2021-10-19 03:24 UTC, moldis commented on code/go/0chain.net/blobbercore/handler/handler.go
> +	r.HandleFunc("/v1/dir/{allocation}", WithJSON(CreateDir)).Methods(http.MethodPut)
@cnlangzi PUT methods is for updates mostly, this one is create should be POST

2021-10-19 03:26 UTC, moldis commented on code/go/0chain.net/blobbercore/reference/ref_walker.go
> +	if d == nil {
Not sure in what case d can be nil?

2021-10-19 07:14 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/handler.go
> +	r.HandleFunc("/v1/dir/{allocation}", WithJSON(CreateDir)).Methods(http.MethodPut)
@moldis  It is designed to work for CREATE/UPDATE. please see directory_test.go

2021-10-19 07:15 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/ref_walker.go
> +	if d == nil {
It prevents crash if some guy write bad code.

2021-10-19 07:18 UTC, moldis commented on code/go/0chain.net/blobbercore/models/migration.go
> +type Migration struct {
I thought gorm supports auto migration with models, what is the purpose of this file?

2021-10-19 07:21 UTC, moldis commented on code/go/0chain.net/blobbercore/models/reference_object.go
> +	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at"` // soft deletion
Instead of defining these fields for each type, you can define type once `type ModelWithTS struct {
	CreatedAt time.Time `gorm:"column:created_at;autoCreateTime"`
	UpdatedAt time.Time `gorm:"column:updated_at;autoUpdateTime:milli"`
}`

And then add datastore.ModelWithTS (example) for each type you want to include CreateAt/UpdateAt and not sure what's the DeleteAt ?

2021-10-19 07:22 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/models/migration.go
> +type Migration struct {
I have tested it .It doesn't work properly for index and constraints. And it is stupid on column type checking. so have to write it by own function.

2021-10-19 07:23 UTC, moldis commented on code/go/0chain.net/blobbercore/reference/dao.go
> +		return it, errors.Throw(constants.ErrEntityNotFound, "alloction_id: "+allocationTx+" path: "+path)
typo here: alloction_id

2021-10-19 07:29 UTC, moldis commented on code/go/0chain.net/blobbercore/reference/ref_walker.go
> +	if d == nil {
@cnlangzi Still not clear, if RefWalker is nil - how anyone can call Name() or anything else?

2021-10-19 07:30 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/models/reference_object.go
> +	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at"` // soft deletion
fixed it. deleted_at already is defined in db. I have no chance to check how it works. It is only a mapping between db and model.

2021-10-19 07:33 UTC, moldis commented on code/go/0chain.net/blobbercore/models/migration.go
> +type Migration struct {
@cnlangzi It seems working fine on the 0box server (it's been many migrations so far), may I know what issues you faced with testing it in index and constraints?

2021-10-20 10:32 UTC, moldis approved these changes
Looks good

2021-10-21 09:23 UTC, lpoli commented on code/go/0chain.net/blobbercore/datastore/postgres.go
> +		SkipDefaultTransaction: true, // https://gorm.io/docs/performance.html#Disable-Default-Transaction
We might desire data consistency to performance. So I don't think we should skip default transaction.  Gorm document clearly says that if we don't require data consistency then we can increase performance by skipping default transaction.

2021-10-21 09:25 UTC, lpoli commented on code/go/0chain.net/blobbercore/filestore/fs_store.go
> -func (fs *FileFSStore) CreateDir(dirName string) error {
Deleting this function under different commit. Commit was related to automigration but this function deletion makes less sense under this commit.

2021-10-21 09:29 UTC, lpoli commented on go.mod
> +replace github.com/0chain/gosdk => ../gosdk
Just a reminder to comment out this line

2021-10-21 09:30 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/datastore/postgres.go
> +		SkipDefaultTransaction: true, // https://gorm.io/docs/performance.html#Disable-Default-Transaction
- In old code, a db transaction is started at every request begin. 
- In new code, we use db.Transaction(func(tx *gorm.DB) error) to start transaction. 
so it is unnecessary to let gorm to do it automatically. Actually, transaction is unnecessary for performance if only a record is added/updated/deleted .

2021-10-21 09:31 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/filestore/fs_store.go
> -func (fs *FileFSStore) CreateDir(dirName string) error {
commit is unnecessary for `CreateDir`.  and `CreateDir` is unnecessary to do anything on local disk. so we don't need it in our filestore interface.

2021-10-21 09:32 UTC, cnlangzi commented on go.mod
> +replace github.com/0chain/gosdk => ../gosdk
will fix it before merging

2021-10-21 09:32 UTC, lpoli commented on code/go/0chain.net/blobbercore/models/reference_object.go
> +	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at"` // soft deletion
Gorm by default implements soft delete, that means, it will update deleted_at column and will only show rows which have deleted_at column value to be null.
We can use other method to retrieve deleted rows. I think its `unscoped` method.

2021-10-21 09:34 UTC, lpoli commented on code/go/0chain.net/blobbercore/models/migration.go
> +			return true
It seems version number priority is not considered. Comparing 0.2.3 with 1.1.3 it will return true.

2021-10-21 09:37 UTC, lpoli commented on code/go/0chain.net/blobbercore/models/migration.go
> +}
If we have to add new scripts to update table schema then it is no different than SQL code. If we cannot make proper use of gorm fields then we should use traditional way(with .sql file)

2021-10-21 09:42 UTC, lpoli commented on code/go/0chain.net/blobbercore/allocation/dao.go
> +	tx := db.Session(&gorm.Session{PrepareStmt: true})
Does it cache query after session is complete?
I see that you have `PrepareStmt` set to true while opening postgres db which is global .

2021-10-21 09:44 UTC, lpoli commented on code/go/0chain.net/blobbercore/allocation/zcn.go
> +func SyncAllocation(allocationTx string) (*models.Allocation, error) {
This refactorization has made code more readable but performance wise it has no effect. Also it is under auto-migration commit.

2021-10-21 09:51 UTC, lpoli commented on code/go/0chain.net/blobbercore/handler/handler.go
> +	r.HandleFunc("/v1/dir/{allocation}", WithJSON(CreateDir)).Methods(http.MethodPut)
I think for create and update both we use post rather than put

2021-10-21 10:07 UTC, lpoli commented on code/go/0chain.net/blobbercore/datastore/postgres.go
> +		SkipDefaultTransaction: true, // https://gorm.io/docs/performance.html#Disable-Default-Transaction
If we are using db.Transaction the we are using transaction already. It only makes sense to use SkipDefaultTransaction if we don't use transaction for read operation.

2021-10-21 10:09 UTC, lpoli commented on code/go/0chain.net/blobbercore/filestore/fs_store.go
> -func (fs *FileFSStore) CreateDir(dirName string) error {
My point is that it will be difficult to review if you put irrelevant file changes under this commit.

This commit message is about automigration but deleting createDir function has no purpose in it.

2021-10-21 10:15 UTC, lpoli requested changes
I suppose by auto-migration we mean adding/updating table schema, adding/updating indexes, etc. Also the migration code has not taken data migration into consideration so this is related to table schema only.

If that can be achieved by gorm fields then it is fine but if we need to create newer scripts then I don't think it is easier approach.

Also please add appropriate files changes under some commit. This commit is related to auto-migration of postgresql schema but has other changes as well.

2021-10-21 11:39 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/handler.go
> +	r.HandleFunc("/v1/dir/{allocation}", WithJSON(CreateDir)).Methods(http.MethodPut)
`The difference between PUT and POST is that PUT is idempotent: calling it once or several times successively has the same effect (that is no side effect), whereas successive identical POST requests may have additional effects, akin to placing an order several times`  https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT#:~:text=The%20difference%20between%20PUT%20and,placing%20an%20order%20several%20times.

that is why I think it is better to implemented as `PUT` instead of `POST`. Because it is a idempotent operation here.

2021-10-21 11:40 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/datastore/postgres.go
> +		SkipDefaultTransaction: true, // https://gorm.io/docs/performance.html#Disable-Default-Transaction
NO. please check it on. https://gorm.io/docs/performance.html#Disable-Default-Transaction

`GORM perform write (create/update/delete) operations run inside a transaction to ensure data consistency, which is bad for performance, you can disable it during initialization`

it is not designed for `read`.

2021-10-21 11:42 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/models/migration.go
> +			return true
Yes. because index is changed.so it must be migrated. 
but 0.2.3 is incorrect one. version is set by developer. why he set it as 0.2.3 if we have 1.1.3 now? 

Anyway, it will work properly if it only has migration script for index.

2021-10-21 11:44 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/filestore/fs_store.go
> -func (fs *FileFSStore) CreateDir(dirName string) error {
I am try to re-implement CreateDir, but it asks to migrate schema to add index. that is why `AutoMigrate` is added here.

2021-10-21 11:46 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/models/migration.go
> +}
please have a look at [README.md](https://github.com/0chain/blobber/blob/fix/break_challenge_on_creatdir/code/go/0chain.net/blobbercore/models/README.md#migrate-tablecolumn-in-gormautomigrate)

2021-10-21 11:51 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/models/migration.go
> +}
gorm AutoMigrate is stupid with some cases.
- reference.PathLevel, it can't know the type as well. so migrate script always be executed. the problem is the migrate script doesn't work. so it always is migrated again and again......
- add foreign key , you have to add embedded objects to let gorm know how to migrate it. eg.   allocations.terms. But advance ORM feature is removed from blobber code.  It is better to let ORM worked with plain object for better performance

so gorm AutoMigrate is not good for everything. We just do something manually if it doesn't work properly with gorm.

2021-10-21 11:58 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/allocation/zcn.go
> +func SyncAllocation(allocationTx string) (*models.Allocation, error) {
have a look at `VerifyAllocationTransaction`. 
- for new allocation, it query db twice with transaction.
- for old allocation , it load allocation and terms with transaction too. so 2 db operations too. but terms are unnecessary for almost request

In new code, Only one query operation without starting a heavy transaction for new/old allocation. and terms will not be loaded too . 
It will improve a lot of performance on it.  Because almost of command will ask to load allocation. if it saves 100ms, 10 times mean 1s.  I don't think it has no effect on performance.  @guruhubb asks to develop blobber as high concurrent request system. Roman is not built one day. We need improve performance as much as possible.

2021-10-21 12:01 UTC, cnlangzi commented
> I suppose by auto-migration we mean adding/updating table schema, adding/updating indexes, etc. Also the migration code has not taken data migration into consideration so this is related to table schema only.
> 
> If that can be achieved by gorm fields then it is fine but if we need to create newer scripts then I don't think it is easier approach.
> 
> Also please add appropriate files changes under some commit. This commit is related to auto-migration of postgresql schema but has other changes as well.


This PR is submitted for `CreateDir`. Other changes are developed for it too. if we split them into other PRs again, our code will still keep smell. 
I would suggest to improve it pice by pice when we are fixing bugs or adding feature if it is possible. 

It is a big challenge if someone assign me an issue to refactor all db code at the same time.  It is real difficult to get it done in time. And we have to stop to work on any features /bugs .

2021-10-21 12:04 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/allocation/dao.go
> +	tx := db.Session(&gorm.Session{PrepareStmt: true})
good question. I need to go through gorm code to double check it.  DryRun is designed for speed up first db call in request.

2021-10-21 12:21 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/allocation/dao.go
> +	tx := db.Session(&gorm.Session{PrepareStmt: true})
It seems is designed as global objects.so it should work with session and global mode. but let's change it with global mode. it should be better than session mode.

https://github.com/go-gorm/gorm/blob/38e55f1117858e49c372e0e7a9f22f9761c7cd8b/gorm.go#L176
```
preparedStmt := &PreparedStmtDB{
		ConnPool:    db.ConnPool,
		Stmts:       map[string]Stmt{},
		Mux:         &sync.RWMutex{},
		PreparedSQL: make([]string, 0, 100),
	}
	db.cacheStore.Store(preparedStmtDBKey, preparedStmt)

	if config.PrepareStmt {
		db.ConnPool = preparedStmt
	}
```

https://github.com/go-gorm/gorm/blob/38e55f1117858e49c372e0e7a9f22f9761c7cd8b/gorm.go#L244
```
if config.PrepareStmt {
		if v, ok := db.cacheStore.Load(preparedStmtDBKey); ok {
			preparedStmt := v.(*PreparedStmtDB)
			tx.Statement.ConnPool = &PreparedStmtDB{
				ConnPool: db.Config.ConnPool,
				Mux:      preparedStmt.Mux,
				Stmts:    preparedStmt.Stmts,
			}
			txConfig.ConnPool = tx.Statement.ConnPool
			txConfig.PrepareStmt = true
		}
	}
```

2021-10-21 12:51 UTC, lpoli commented on code/go/0chain.net/validatorcore/storage/models.go
> +		if len(childRef.GetHash()) > 0 {
When will it be equal to 0?

2021-10-21 13:14 UTC, lpoli commented on code/go/0chain.net/blobbercore/reference/referencepath.go
> +					Where(SQLWhereGetByAllocationTxAndPath, allocationID, p).
I suppose it requires parent path for the query. Please fix this.
Also this NewRefWalker struct is complex for other developers. Previous code was easier to understand.
Performance wise its same as previous.

2021-10-21 13:20 UTC, lpoli commented on code/go/0chain.net/blobbercore/reference/ref_walker.go
> +	if d == nil {
Since it is static language and we have many tests written I don't think we have to become too cautious .  Returning rootPath for RefWalker typed nil value when Name() is called seems issue to me.

2021-10-21 13:27 UTC, lpoli commented on code/go/0chain.net/blobbercore/reference/ref.go
> +		return "", nil
Need to be careful here. We can upload file to non-existing directories. For eg: `/d1/d2/d3/d4/file.txt`. So in this case if d1, d2, d3 and d4 did not exist then it will be created and it will have hash.
Later on file.txt can be deleted and directories can still have hash.

If returning empty string won't cause any issues then its good to go otherwise it is a bug.

2021-10-21 13:28 UTC, lpoli commented on code/go/0chain.net/blobbercore/reference/ref.go
> +		if len(childRef.Hash) > 0 {
So here I see that if a child is empty directory then hash will equal to 0.

Again we need to be careful as it will impact whole system.

2021-10-21 13:35 UTC, lpoli commented on code/go/0chain.net/blobbercore/handler/directory.go
> +			dir.MerkleRoot = ""
Why initialize with default value? It can be removed along with other lines

2021-10-21 13:38 UTC, lpoli commented on code/go/0chain.net/blobbercore/handler/directory.go
>  func CreateDir(ctx *Context) (interface{}, error) {
My only concern over this function is: Do we only need directory info as reference_object?

I had previously checked how file was stored in a directory. I think file's hash was used by dividing it to 3,3,3,7 characters to store file.

2021-10-21 13:44 UTC, lpoli requested changes
Empty dir hash has been set to empty string. I've commented about it. Please check.
Also this RefWalker struct is a bit complex. Its easy for another developer to make error by using this structure. Previous code was easier to understand.

Being extra cautious seemed redundant to me. It would be better to return error rather than to provide root path which might be future bug.

2021-10-21 13:49 UTC, lpoli commented
> > I suppose by auto-migration we mean adding/updating table schema, adding/updating indexes, etc. Also the migration code has not taken data migration into consideration so this is related to table schema only.
> > If that can be achieved by gorm fields then it is fine but if we need to create newer scripts then I don't think it is easier approach.
> > Also please add appropriate files changes under some commit. This commit is related to auto-migration of postgresql schema but has other changes as well.
> 
> This PR is submitted for `CreateDir`. Other changes are developed for it too. if we split them into other PRs again, our code will still keep smell. I would suggest to improve it pice by pice when we are fixing bugs or adding feature if it is possible.
> 
> It is a big challenge if someone assign me an issue to refactor all db code at the same time. It is real difficult to get it done in time. And we have to stop to work on any features /bugs .

It can be under same PR but I think under auto-migration commit message there were other changes that was irrelevant to auto-migration.

2021-10-21 13:56 UTC, lpoli commented on code/go/0chain.net/blobbercore/models/migration.go
> +			return true
Then what is the point of checking if developer will put correct one?

2021-10-21 14:04 UTC, lpoli commented on code/go/0chain.net/blobbercore/models/migration.go
> +}
So do you mean that by automation scripts we are only supplementing migration that GORM would otherwise be unable to migrate?

btw I did not get your first point. Can you please explain it?

2021-10-22 00:44 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/ref_walker.go
> +	if d == nil {
app should be `Robustness`. it mean we can't leave any crash chance to consumer. eg

have a think what happens if it is removed?
```
var refwalker *RefWalker

ref.Name()
```

2021-10-22 00:46 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/models/migration.go
> +			return true
you can think there are 3 independent versions. Actually, they are .

2021-10-22 00:46 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/models/migration.go
> +}
try to test it on local  gorm.AutoMigrate(&ReferenceObject{}). you will see what happens.

2021-10-22 01:04 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/referencepath.go
> +					Where(SQLWhereGetByAllocationTxAndPath, allocationID, p).
No. there are two issues on old code for some cases. just no guy to test and fix it. do you have a check on what the sql it generated is?

it is generated like `select * from reference_objects where (((parent_path='/d1/d2/d3/d4/d5' and allocation_id='cff048aaa3bdd858d0f52bfe833ef441464d79089e2d44c6272c3f8a1f50977c) or (prarent_path='/d1/d2/d3/d4' and allocation_id='cff048aaa3bdd858d0f52bfe833ef441464d79089e2d44c6272c3f8a1f50977c')) or.......) and (path=/d1/d2/d3/d4/d5/d6' and allocation_id='cff048aaa3bdd858d0f52bfe833ef441464d79089e2d44c6272c3f8a1f50977c' order by level,paht.

-  it will hit `max_expr_depth` or `max_stack_depth` issue on postgres if some guy has a big ref tree(eg. depth is 100). And his allocation will never work again. Because getRootRef might stop to work. It will kill almost of commands.
- i don't think too many `Or`  in where is not a performance issue.

2021-10-22 01:06 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/ref.go
> +		return "", nil
it hides empty dir in ref's Hash. if not, we hit the lock issue again. that is why it is changed. so we can free feel to create /delete empty dir as much as we want. if not, you need calculate hash , and send transaction to blockchain , and wait for verification form sharder.

2021-10-22 01:12 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/ref.go
> +		if len(childRef.Hash) > 0 {
It is opposite to break system, it does compatible with it. empty dir will not effect old hash, it is invisible for it.

2021-10-22 01:13 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/directory.go
>  func CreateDir(ctx *Context) (interface{}, error) {
yes , we need it in db. if not, zbox list will not work.

2021-10-22 01:15 UTC, cnlangzi commented on code/go/0chain.net/validatorcore/storage/models.go
> +		if len(childRef.GetHash()) > 0 {
empty dir

2021-10-22 07:01 UTC, lpoli commented on code/go/0chain.net/blobbercore/datastore/postgres.go
> +		SkipDefaultTransaction: true, // https://gorm.io/docs/performance.html#Disable-Default-Transaction
Yes that's what I mean.
We must use transaction for write operations. While for read operations we want to skip it.

2021-10-22 07:13 UTC, lpoli commented on code/go/0chain.net/blobbercore/reference/referencepath.go
> +					Where(SQLWhereGetByAllocationTxAndPath, allocationID, p).
This function is required to calculate new Hashes when some file changes.
It takes all refs under subdirectories and gradually calculates hashes. Previous query worked with "parent_path" in query and now you are just querying with "path". I think this is a bug.

2021-10-22 07:17 UTC, lpoli commented on code/go/0chain.net/blobbercore/reference/ref.go
> +		return "", nil
Consider a filepath `/d1/d2/d3/d4/file.txt` and `file.txt` is deleted. Of course, d4 ref will have empty hash but what happens to d1, d2 and d3 ref?

2021-10-22 07:18 UTC, lpoli commented on code/go/0chain.net/blobbercore/handler/directory.go
>  func CreateDir(ctx *Context) (interface{}, error) {
You misunderstood my concern. But its fine.

2021-10-22 13:22 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/ref_walker.go
> +	if d == nil {
hi guys, do you know `Dbc`?  [Design by contract](https://en.wikipedia.org/wiki/Design_by_contract)

You must assert any input without valid value.if not, static check fails. Your app never crash by nil input like `nInvalid memory address or nil pointer dereference in golang`, `NullReferenceException in c#` and ` java.lang.NullPointerException in Java`

In my opinion, it is a basic rule to prevent app crash by nil/null point on coding.

2021-10-22 13:33 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/referencepath.go
> +					Where(SQLWhereGetByAllocationTxAndPath, allocationID, p).
No, that is not true. please have check it again. it works similar old logic, just split them into one dir by one dir instead of getting them in a query, and from root to last leaf .

- Top() will jump to root dir
- loop Forward() till done. all dir will be loaded if it is necessary. if not, we can stop and return anytime.

2021-10-22 13:39 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/reference/ref.go
> +		return "", nil
good question. I think `Hash` should be updated with "".  Because all nodes are re-calculated when root is calculated. And all changes are saved with root.  And I will test it again to verify it.

2021-10-22 14:05 UTC, lpoli commented on code/go/0chain.net/blobbercore/reference/ref_walker.go
> +	if d == nil {
I fairly checked the above link. It suggests that client and supplier are obliged to fulfill certain preconditions and postconditions. Preconditions are to be fulfilled by client that is imposed by supplier and Postconditions are fulfilled by supplier that is imposed by client.

In our case we have to have precondition to not allow nil value and return error rather than let application crash.
My point was, for a nil value RefWalker it defaulted to rootpath "/", which might be issue later on.

2021-10-23 14:14 UTC, Sriep commented
Why do we need the auto migration changes coupled to the `createdir` changes? 

I find it often useful to initially make a compound PR with all the changes I want. Once completed I can usually see the best way to split the PR up into disjoint subsets.

2021-10-23 17:00 UTC, kushthedude requested changes
This PR not only re-implements the createDir but revamps the core architecture of how the handlers have been written & how we communicate with the db object at the moment.

My suggestions here would be to separate this monolithic PR into three small PRs:
- Addition of dao & auto-migrate
- Revamping the createDir handler
- Revamping the reference handlers

Functions which are related for interacting with the context to populate the request headers are completely unnecessary as once WASM is up we will deprecate this old handler & move to gRPC handlers which are present in the code. A point to note over here is, gRPC handlers are already revamping the context & headers logic by fetching the headers dynamically from request & passing into context.

2021-10-23 17:00 UTC, kushthedude commented on code/go/0chain.net/blobbercore/allocation/dao.go
> +	if !errors.Is(result.Error, gorm.ErrRecordNotFound) {
Can you move the dao integration & revamping to a separate PR?

2021-10-23 17:00 UTC, kushthedude commented on code/go/0chain.net/blobbercore/handler/context.go
> +
This is completely unrelated to the create-dir but is a more generic implementation of the HTTP request/response manipulations. This is not required since gRPC code will already override this hacks for json response conversion.

2021-10-23 17:00 UTC, kushthedude commented on code/go/0chain.net/blobbercore/models/migration.go
> +func (m *Migration) After(latest *Migration) bool {
Why are we adding models implementation & migration thing in the same PR which is already more than a monolith?

2021-10-25 01:48 UTC, lpoli commented on code/go/0chain.net/blobbercore/reference/referencepath.go
> +					Where(SQLWhereGetByAllocationTxAndPath, allocationID, p).
That I can see. But you are retrieving refs of some path while we need direct child refs of some path.

2021-12-28 15:47 UTC, closed without merging