Create dir logic added if given path is not available.
0chain/blobber pull request #446
Opened 2021-11-26 18:31 UTC by princeparmar

in copy command if given path is not available need to create whole tree and then copy that file.

Signed-off-by: Pradip Parmar <pradip@alfa-creator.com>

2021-11-29 01:52 UTC, cnlangzi requested changes
please check https://github.com/0chain/blobber/blob/7d4af78d867ea54b44e48aed2104df2038df2d85/code/go/0chain.net/blobbercore/reference/referencepath.go#L53 as example

2021-11-29 01:52 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
> +func createDir(ctx context.Context, connectionID, allocationID, clientID, dirPath string) error {
hmm. it seems is not on right direction. I think we can add folders on RefTree only like '/'. and it can be saved in db.

2021-12-02 03:56 UTC, cnlangzi requested changes

2021-12-02 03:56 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
>  	destRef, err = reference.GetReference(ctx, allocationID, destPath)
```suggestion
	destRef, err = reference.Mkdir(ctx, allocationID, destPath)
	if err != nil || destRef.Type != reference.DIRECTORY {
		return nil, common.NewError("invalid_parameters", "Invalid destination path. Should be a valid directory.")
	}
```

```
// Mkdir create dirs if they don't exits. do nothing if dir exists. last dir will be returned
func Mkdir(ctx context.Context, allocationID string, path string) (*Ref, error) {

	dirRef := &Ref{}
	db := datastore.GetStore().GetTransaction(ctx)

	dirs := strings.Split(path, "/")
	parentPath := ""
	currentPath := ""

	for _, dir := range dirs {

		currentPath += "/" + dir

		var ref *Ref

		err := db.Where(&Ref{AllocationID: allocationID, Path: currentPath}).First(ref).Error

		if err == nil {
			dirRef = ref
			parentPath = currentPath
			continue
		}

		// dir doesn't exists , create it
		if errors.Is(err, gorm.ErrRecordNotFound) {
			ref = &Ref{Type: DIRECTORY, AllocationID: allocationID, Name: dir, Path: currentPath, ParentPath: parentPath, PathLevel: 1}
			err = db.Create(ref).Error
			if err != nil {
				return nil, err
			}

			dirRef = ref
			parentPath = currentPath
			continue
		} else {
			// unexpected sql error
			return nil, err
		}
	}

	return dirRef, nil

}
```

2021-12-02 03:57 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
>  	destRef, err = reference.GetReference(ctx, allocationID, destPath)
a simple demo code, please test it fully on local about WriteMarker issue

2021-12-03 19:55 UTC, stewartie4 commented
could a system test be added for this new behaviour please?
https://github.com/0chain/system_test/blob/master/tests/cli_tests/zboxcli_file_copy_test.go
thanks

2021-12-03 21:58 UTC, cnlangzi commented
> could a system test be added for this new behaviour please? https://github.com/0chain/system_test/blob/master/tests/cli_tests/zboxcli_file_copy_test.go thanks

@princeparmar  please get `integration-tests` fixed first, and follow the [guideline](https://github.com/0chain/system_test#run-tests-against-an-existing-0chain-network-locally) to add system_test. thanks.

2021-12-03 21:59 UTC, cnlangzi commented
if you want to run system_test on github action, please use `blobber:merge` image

2021-12-04 12:07 UTC, cnlangzi approved these changes

2021-12-04 12:07 UTC, merged

2021-12-04 14:54 UTC, stewartie4 commented
have system tests been ran/updated before this merge?