handling for delete root
0chain/blobber pull request #453
Opened 2021-12-04 21:12 UTC by princeparmar

added handling for delete root

2021-12-06 03:44 UTC, cnlangzi requested changes
@princeparmar  it is updated by an example code. please help to check and test it fully
- delete root dir
- list files
- upload a new file
- list files
- delete sub dir
- list files
- upload a new file
- list files

thanks.

2021-12-30 01:53 UTC, princeparmar commented
@cnlangzi please review this.

2021-12-30 04:02 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| 0boxcli  | bug/issue-451-delete-root  |
| 0walletcli  | staging  |
| 0chain  | staging  |
| blobber  | bug/issue-451-delete-root  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2021-12-31 03:19 UTC, cnlangzi approved these changes

2021-12-31 03:20 UTC, merged