removed physical createdir, updated createdir default size.
0chain/blobber pull request #491
Opened 2021-12-31 16:57 UTC by princeparmar

fixed size and block values in newly created dir.

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
- zbox: N/A
- zwalelet: N/A
- gosdk: N/A
- 0chain: N/A
- system_test: N/A

2022-01-02 08:34 UTC, cnlangzi requested changes

2022-01-02 08:34 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/filestore/fs_store.go
>  func (fs *FileFSStore) CreateDir(dirName string) error {
CreateDir should be removed from `Store` interface

2022-01-02 08:34 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/allocation/newfilechange.go
>  	newDir.WriteMarker = allocationRoot
I am not sure if allocationRoot is correct WriteMarker for it. what is allocationRoot here?
It seems is unnecessary on the `Mkdir`. WriteMarker seems is designed for transaction on blockchain.
please double check it.

2022-01-06 02:53 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/issue-155-remove-size-check-create-dir  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | bug/issue-329-incorrect-ref-value  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-01-16 13:01 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/issue-155-remove-size-check-create-dir  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | bug/issue-329-incorrect-ref-value  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-01-17 02:49 UTC, cnlangzi approved these changes

2022-01-17 03:54 UTC, merged