Optimize/download
0chain/blobber pull request #526
Opened 2022-02-03 10:16 UTC by lpoli

This PR contains the following changes:
1. Remove redundancies
2. Make authticket mandatory for clients other than allocation owner
3. Change tests for authticket being mandatory

2022-02-04 05:01 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | optimize/download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-04 12:13 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | hotfix/staging-stabilization  |
| blobber  | optimize/download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-09 05:11 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/public-share-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | optimize/download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-09 13:59 UTC, dabasov approved these changes
lgtm

2022-02-09 13:59 UTC, dabasov commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
> -			encMsg := &zencryption.EncryptedMessage{}
it is the same as new()

2022-02-09 14:01 UTC, cnlangzi requested changes, later dismissed
please get system-test passed first. thanks.

2022-02-10 07:55 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/download-test  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | fix/public-share-issue  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | optimize/download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-10 07:59 UTC, merged