remove path a file
0chain/blobber pull request #530
Opened 2022-02-06 06:16 UTC by md-miran

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
- zbox:
- zwalelet:
- gosdk:
- 0chain:
- system_test:

2022-02-06 07:01 UTC, lpoli requested changes
This checking need no extra function.
Simply get a reference and check its `refType`

2022-02-06 07:01 UTC, lpoli commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
> +		if err == nil {
This return of `false` when err != nil is erroneous logically

2022-02-06 07:08 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | f_miran_blobber_file_path  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-14 02:38 UTC, cnlangzi requested changes

2022-02-14 02:38 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
> +				dirReference, _ := reference.GetReference(ctx, allocationObj.ID, fileDir)
it is not worth to get whole reference record. it is enough to  read  `type` only.

2022-03-03 03:46 UTC, closed without merging