change data reading from form to header for download.
0chain/blobber pull request #550
Opened 2022-02-22 16:25 UTC by princeparmar

Signed-off-by: Pradip Parmar <pradip@alfa-creator.com>

Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master BEFORE merging this PR

Associated PRs (Link as appropriate):
- zbox:
- zwalelet:
- gosdk:
- 0chain:
- system_test:

2022-02-22 16:30 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | feature/545-migrate-querydata-to-header-download  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/545-migrate-querydata-to-header-download  |
| authorizer  | staging  |
| 0box  | feature/545-migrate-querydata-to-header-download  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-23 02:31 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | feature/545-migrate-querydata-to-header-download  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/545-migrate-querydata-to-header-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-23 03:56 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/545-migrate-querydata-to-header-download  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/545-migrate-querydata-to-header-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-24 00:13 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/545-migrate-querydata-to-header-download  |
| zboxcli  | feature/545-migrate-querydata-to-header-download  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/545-migrate-querydata-to-header-download  |
| authorizer  | staging  |
| 0box  | feature/545-migrate-querydata-to-header-download  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-24 09:03 UTC, cnlangzi commented
@hm90121  api document should be updated for this PR. please talk to @princeparmar about detail.

2022-02-24 09:23 UTC, cnlangzi approved these changes
LGTM

2022-02-24 09:53 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/545-migrate-querydata-to-header-download  |
| zboxcli  | feature/545-migrate-querydata-to-header-download  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/545-migrate-querydata-to-header-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-24 10:13 UTC, cnlangzi requested changes

2022-02-24 10:13 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/handler_test.go
> +					r, err := http.NewRequest(http.MethodPost, url.String(), nil)
http.MethodPost should be updated with http.MethodGet. and please move all download tests to hanlder_download_test.go.  There are too many tests on handler_test.go. it is very difficult to read and debug.

2022-02-25 00:03 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/545-migrate-querydata-to-header-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-26 17:33 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | staging  |
| zboxcli  | feature/545-migrate-querydata-to-header-download  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/545-migrate-querydata-to-header-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-27 15:51 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | feature/545-migrate-querydata-to-header-download  |
| zboxcli  | feature/545-migrate-querydata-to-header-download  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | feature/545-migrate-querydata-to-header-download  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-02-27 15:53 UTC, cnlangzi approved these changes

2022-02-27 16:57 UTC, merged