Feature/467 new fields for writemarker
0chain/blobber pull request #577
Opened 2022-03-08 02:35 UTC by princeparmar

### Changes

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-03-09 01:02 UTC, cnlangzi requested changes
content_hash and name are missing when it is sent to blockchain on https://github.com/0chain/blobber/blob/9e894f5f199cc66407528979bbf5c24f8994dd6b/code/go/0chain.net/blobbercore/writemarker/protocol.go#L100

2022-03-09 01:02 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/datastore/postgres_releases.go
> +		Version:   "0.1.0",
try to use `AutoMigrate` for write_markers table.

2022-03-09 01:02 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/handler/object_operation_handler.go
> +	writemarkerObj.WM.LookupHash = rootRef.LookupHash
I think we should save the lookup_hash of the current file, not root.

2022-03-09 01:02 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/writemarker/entity.go
> +	ContentHash            string           `gorm:"column:content_hash" json:"content_hash"`
it is unnecessary to save content_hash and name on `write_markers` table to save disk space on postgres. 
we can read them from db by lookup_hash when it is sent to blockchain.

2022-03-09 01:02 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/writemarker/entity.go
> +	ContentHash            string           `gorm:"column:content_hash" json:"content_hash"`
it is unnecessary to save content_hash and name on `write_markers` table to save disk space on postgres. 
we can read them from db by lookup_hash when it is sent to blockchain.

2022-04-25 07:05 UTC, peterlimg commented
@cnlangzi any updates about this PR.

2022-04-25 07:32 UTC, cnlangzi commented
> @cnlangzi any updates about this PR.

will fix this PR soon

2022-04-25 07:32 UTC, cnlangzi commented
A new PR will be fixed to fix #467

2022-04-25 07:32 UTC, closed without merging