Modify/read marker2
0chain/blobber pull request #582
Opened 2022-03-10 12:26 UTC by lpoli

This PR contains the following changes:

    Change ReadMarker's ReadCounter to ReadSize
    Remove latest ReadMarker logic from the code as it is useless with current implementation
    Modify pendings table to accommodate above changes
    Reduce unnecessary functions and function calls in worker in readmarker package

This PR solves the issue https://github.com/0chain/blobber/issues/507

2022-03-10 16:20 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/read-marker  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | modify/read-marker  |
| zwalletcli  | staging  |
| 0chain  | modify/read-marker  |
| blobber  | modify/read-marker2  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-14 12:03 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | modify/read-marker  |
| zwalletcli  | staging  |
| 0chain  | modify/read-marker  |
| blobber  | modify/read-marker2  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-16 11:29 UTC, peterlimg requested changes

2022-03-16 11:29 UTC, peterlimg commented on code/go/0chain.net/blobbercore/allocation/entity.go
>  		err = tx.Create(p).Error
The p is empty here, is this an intended behavior or a mistake?

2022-03-16 11:29 UTC, peterlimg commented on code/go/0chain.net/blobbercore/allocation/entity.go
> +			allocation_id = ?`
If the blobber_id param is not being used, please remove it.

2022-03-16 11:29 UTC, peterlimg commented on code/go/0chain.net/blobbercore/allocation/entity.go
> +				blobber_id = ?`
Does WritePool have the blobber_id

2022-03-17 02:24 UTC, lpoli commented on code/go/0chain.net/blobbercore/allocation/entity.go
>  		err = tx.Create(p).Error
This function should have been deleted. Forgot to delete.
Will fix this

2022-03-17 02:32 UTC, lpoli commented on code/go/0chain.net/blobbercore/allocation/entity.go
> +				blobber_id = ?`
No it does not.
Fixed now. Thank you.

2022-03-17 04:12 UTC, peterlimg approved these changes
lgtm

2022-03-27 15:02 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | fix/download-cost-calculation  |
| gosdk  | modify/read-marker  |
| zboxcli  | modify/read-marker  |
| zwalletcli  | staging  |
| 0chain  | modify/read-marker  |
| blobber  | modify/read-marker2  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-03-27 15:04 UTC, merged