Alert1
0chain/blobber pull request #611
Opened 2022-03-29 13:09 UTC by vinayakgautamops

created merge_alert.yaml 
### Changes

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-03-31 14:52 UTC, m-s-a-c requested changes

2022-03-31 14:52 UTC, m-s-a-c commented on .github/workflows/merge_alert.yaml
> +      - name: Run step when a 0chain.yaml file changes
Please correct this @vinayakgautamops

2022-03-31 14:52 UTC, m-s-a-c commented on .github/workflows/merge_alert.yaml
> +      - name: Run step when a sc.yaml file changes
please correct sc.yaml in name: @vinayakgautamops

2022-04-02 16:35 UTC, vinayakgautamops commented
closed

2022-04-02 16:35 UTC, closed without merging