Skip automigrating for existing tables
0chain/blobber pull request #705
Opened 2022-05-31 11:07 UTC by lpoli

### Fixes
This PR will fix issue that occurs when gorm tries to automigrate schema to already existing tables in the database.

2022-06-01 00:14 UTC, cnlangzi commented
I don't how it works if a table is configured as keep_tables on yaml file, and there are new columns should be added. let's waiting for @peterlimg  to review

2022-06-02 15:10 UTC, cnlangzi requested changes
I think you have some misunderstand about `AutoMigrate` on schema.

2022-06-02 15:10 UTC, cnlangzi commented on code/go/0chain.net/blobbercore/automigration/automigration.go
>  		err := db.Migrator().DropTable(tableName)
We need `Migration`. `drop` and `create` is `recreate` with fresh data, is not `schema migration`.

2022-06-02 15:10 UTC, cnlangzi commented on config/0chain_blobber.yaml
> +  automigrate: false # true to automigrate with gorm's Automigration
it is unnecessary. AutoMigrate should always be checked. gorm will compare schema between Models and database, and build upgrade scripts for new tables, new columns, changed columns.....

AutoMigrate is `migrate schema without losing data`.

2022-06-02 15:54 UTC, lpoli commented on config/0chain_blobber.yaml
> +  automigrate: false # true to automigrate with gorm's Automigration
@cnlangzi you got stale view of the PR.
I had already made the changes that you have requested.

2022-06-02 22:46 UTC, cnlangzi requested changes

2022-06-02 22:46 UTC, cnlangzi commented on code/go/0chain.net/blobber/config.go
> +	config.Configuration.Version = viper.GetString("version")
add `version` in yaml file, it will have the same issue with keep_tables. it has a deployment issue. why it is required here for AutoMigrate?

2022-06-02 22:48 UTC, cnlangzi commented on config/0chain_blobber.yaml
> +  automigrate: false # true to automigrate with gorm's Automigration
sorry, github view doesn't refresh properly.

2022-06-03 06:31 UTC, cnlangzi requested changes

2022-06-03 06:31 UTC, cnlangzi commented on config/0chain_blobber.yaml
> +version: "1.0"
it is configured for nothing. it is better to remove it for now.

2022-06-03 06:34 UTC, cnlangzi approved these changes
LGTM

2022-06-03 09:40 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | fix/automigrate-existing-table-issue  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-06-04 01:46 UTC, merged