Remove user write pools
0chain/blobber pull request #725
Opened 2022-06-13 13:58 UTC by Sriep

### Changes
Changes to support single write pool. 
Some syntax fixes for currency changes (int64 -> uint64)

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:https://github.com/0chain/0chain/pull/1465
- gosdk:https://github.com/0chain/gosdk/pull/490
- system_test: https://github.com/0chain/system_test/pull/315
- zboxcli:https://github.com/0chain/zboxcli/pull/258
- zwalletcli:
- Other: ...

2022-06-22 13:31 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pools  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-06-22 17:32 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-06-27 21:39 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-05 12:09 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-07 12:35 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-07 19:14 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-12 11:21 UTC, peterlimg requested changes
Please fix the lint errors, thanks.

2022-07-12 11:21 UTC, peterlimg commented on code/go/0chain.net/core/transaction/entity.go
> +	WritePool      int64                `json:"write_pool"`
Use uint64 for coin balance

2022-07-12 11:21 UTC, peterlimg commented on code/go/0chain.net/blobbercore/allocation/protocol.go
> +		WritePool int64  `json:"write_pool"`
Use uint64 for balance

2022-07-12 13:37 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | remove_write_pool  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-12 16:18 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | remove_write_pools  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-22 01:48 UTC, peterlimg approved these changes
lgtm, please fix the conflicts and system tests

2022-07-25 10:01 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-26 17:06 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-26 18:44 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | remove/writepool  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | remove_write_pool  |
| zwalletcli  | staging  |
| 0chain  | write_pools  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-26 21:15 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | remove_write_pools  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-26 21:15 UTC, merged