Modify/datetime
0chain/blobber pull request #748
Opened 2022-07-06 14:38 UTC by lpoli

### Changes

### Fixes

### Tests
Tasks to complete before merging PR:
- [ ]  Ensure system tests are passing. If not [Run them manually](https://github.com/0chain/blobber/actions/workflows/system_tests.yml) to check for any regressions :clipboard:
- [ ]  Do any new system tests need added to test this change? do any existing system tests need updated? If so create a PR at [0chain/system_test](https://github.com/0chain/system_test)
- [ ]  Merge your system tests PR to master AFTER merging this PR

### Associated PRs (Link as appropriate):
- 0chain:
- gosdk:
- system_test:
- zboxcli:
- zwalletcli:
- Other: ...

2022-07-11 13:44 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | modify/datetime  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/datetime  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-12 03:57 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | master  |
| gosdk  | modify/datetime  |
| zboxcli  | modify/datetime  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/datetime  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-13 11:49 UTC, service-0chain commented
Manual system tests [failure] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/datetime  |
| gosdk  | modify/datetime  |
| zboxcli  | modify/datetime  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/datetime  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-15 12:40 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | FALSE  |
| system-tests  | modify/datetime  |
| gosdk  | modify/datetime  |
| zboxcli  | modify/datetime  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/datetime  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | staging  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-22 12:08 UTC, peterlimg requested changes

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobber/worker.go
> +			break loop
We can return here instead of using the label

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobber/worker.go
> +			break loop
return

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobber/worker.go
> +			break loop
return

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobbercore/allocation/newDirchange.go
> +package allocation
Rename file to newdirchange.go

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobbercore/allocation/newDirchange.go
> +	fmt.Printf("\n\nApplying change for direcory change\n\n")
Use logging please

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobbercore/allocation/newDirchange.go
> +	return nil
Not implemented or not needed ?

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobbercore/allocation/newDirchange.go
> +			if child.Name == fields[i] {
We need to check if file exists that has the same name as the dir

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobbercore/allocation/newfilechange.go
> -type NewFileChange struct {
Is this NewFileChange be replaced by the UploadFileChanger?

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobbercore/reference/object.go
> +				fmt.Printf("\nParent ref: %s\n\n", ref.Path)
Use logging or remove if it's for debugging

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobbercore/reference/ref.go
> +			err = r.SaveDirRef(ctx)
This defer actions would call the r.SaveDirRef when there's no child.

2022-07-22 12:08 UTC, peterlimg commented on code/go/0chain.net/blobbercore/reference/referencepath.go
> +// func GetDeletedRefs(ctx context.Context, allocationID, updatedDate, offsetPath, offsetDate string, pageLimit int, dateLayOut string) (refs *[]PaginatedRef, totalPages int, newOffsetPath, newOffset
Clean up the commented code if not used

2022-07-22 13:27 UTC, lpoli commented on code/go/0chain.net/blobbercore/allocation/newDirchange.go
> +	return nil
Required for the interface matching but implementation is not required

2022-07-22 13:30 UTC, lpoli commented on code/go/0chain.net/blobbercore/allocation/newDirchange.go
> +			if child.Name == fields[i] {
Here we don't need to check because if I get referencePath of path `/a/b/c/d.txt` then `/`, `/a`, `/a/b` and `/a/b/c` are naturally directories.

For `d.txt` we don't need to check because it is checked already if `/a/b/c/d.txt` exists.

2022-07-22 13:30 UTC, lpoli commented on code/go/0chain.net/blobbercore/allocation/newfilechange.go
> -type NewFileChange struct {
Yes

2022-07-24 05:06 UTC, peterlimg approved these changes
lgtm

2022-07-28 04:58 UTC, service-0chain commented
Manual system tests [success] with the following config
| config  | value |
| ------------- | ------------- |
| tests skipped  | TRUE  |
| system-tests  | master  |
| gosdk  | NOT OVERRIDDEN  |
| zboxcli  | staging  |
| zwalletcli  | staging  |
| 0chain  | staging  |
| blobber  | modify/datetime  |
| authorizer  | staging  |
| 0box  | staging  |
| 0block  | staging  |
| 0dns  | staging  |
| explorer  | master  |
| 0proxy  | staging  |
| 0search  | staging  |

2022-07-28 04:59 UTC, merged