Blobber consensus with unavailable sharders 34
0chain/blobber pull request #79
Opened 2021-04-17 03:26 UTC by andrenerd

2021-04-18 13:07 UTC, shravanshetty1 approved these changes
Issue title is no longer relevant. The changes include retry mechanism for sharder request, and basic refactoring. If this was the intention it looks fine.

2021-04-18 15:25 UTC, Sriep requested changes

2021-04-18 15:25 UTC, Sriep commented on code/go/0chain.net/core/transaction/http.go
> +				Timeout: 5 * time.Second, // TODO: better create a const
If you think this should be a const, then create a const. Its a trival change.

2021-04-18 15:25 UTC, Sriep commented on code/go/0chain.net/core/transaction/http.go
> +	// 		if res.StatusCode != 200 {
Why is there this lump of commented out code? If you must do someting delete it; to prevent others from being destracted by it.

2021-04-18 15:25 UTC, Sriep commented on code/go/0chain.net/core/transaction/http.go
> +			Timeout:   time.Second * 10, // TODO: create a const
Again, create the const not the todo.

2021-04-18 15:25 UTC, Sriep commented on code/go/0chain.net/core/transaction/http.go
> +			// TODO: better create an utility function as isAvailable or so
If you think there should be a unitlity function, then create it. Does this block of code get used anywhere else? if so then it looks like a good idea.

2021-04-18 20:36 UTC, andrenerd commented
@Sriep thanks.
cleaned up. please, review again.
ps. the long commented code blocks are legacy code. not related to the issue. so keeping them commented.

2021-04-19 10:47 UTC, Sriep commented
Thanks. 
Resolve review issues as they are handled (There is a resolve button). If the issue is not resolved that indicates it is still a problem, blocking merging.
Also, if you want to discuss an issue, use the reply option attached to the issue.

2021-04-19 13:32 UTC, andrenerd commented
@Sriep 
oops, sorry. 
done. could it be merged now?

2021-04-19 14:15 UTC, Sriep approved these changes

2021-04-19 14:19 UTC, merged